[package]
name = "dino"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
panic-halt = "1.0.0"
rtt-target = "0.6.2"
stm32f4xx-hal = { version = "0.23.0", features = ["stm32f407"] }
nb = "1.1"
