[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32F411CEUx'
rustflags = [
  # `flip-link` moves stack at the end of flash
  #"-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  #"-C", "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  #"-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"

[profile.dev]
debug = true
lto = true
panic = "abort"

[profile.release]
debug = true
lto = true
opt-level = "s"
panic = "abort"